name: StealthyStash
on:
  push:
    branches-ignore:
      - '*WIP'
env:
  PACKAGE_NAME: StealthyStash      
jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    container: ${{ matrix.swift.nightly && format('swiftlang/swift:nightly-{0}-{1}', matrix.swift.version, matrix.os) || format('swift:{0}-{1}', matrix.swift.version, matrix.os) }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: [noble, jammy]
        swift:
          - version: "5.8"
          - version: "5.9"
          - version: "5.10"
          - version: "6.0"
          - version: "6.1"
          - version: "6.1"
            nightly: true
          - version: "6.2"
            nightly: true
        exclude:
          - os: noble
            swift:
              version: "5.8"
          - os: noble
            swift:
              version: "5.9"
    steps:
      - uses: actions/checkout@v4
      - uses: brightdigit/swift-build@v1.3.4
      - uses: sersoft-gmbh/swift-coverage-action@v4
        id: coverage-files
        with:          
          fail-on-empty-output: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4       
        with:
          fail_ci_if_error: true
          flags: swift-${{ matrix.swift.version }},ubuntu
          verbose: true        
          token: ${{ secrets.CODECOV_TOKEN }}  
          files: ${{ join(fromJSON(steps.coverage-files.outputs.files), ',') }}
  build-windows:
    name: Build on Windows
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on: [windows-2022, windows-2025]
        include:
          - swift-version: swift-5.8-release
            swift-build: 5.8-RELEASE
          - swift-version: swift-5.9-release
            swift-build: 5.9-RELEASE
          - swift-version: swift-5.10-release
            swift-build: 5.10-RELEASE
          - swift-version: swift-6.0-release
            swift-build: 6.0-RELEASE
          - swift-version: swift-6.1-release
            swift-build: 6.1-RELEASE
          - swift-version: swift-6.2-branch
            swift-build: 6.2-DEVELOPMENT-SNAPSHOT-2025-09-06-a
    steps:
      - uses: actions/checkout@v4
      - uses: brightdigit/swift-build@v1.3.4
        with:
          windows-swift-version: ${{ matrix.swift-version }}
          windows-swift-build: ${{ matrix.swift-build }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5    
        with:
          fail_ci_if_error: true
          flags: swift-${{ matrix.swift-version }},windows
          verbose: true        
          token: ${{ secrets.CODECOV_TOKEN }}
          os: windows
          swift_project: StealthyStash
  build-macos:
    name: Build on macOS
    env:
      PACKAGE_NAME: StealthyStash
    runs-on: ${{ matrix.runs-on }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      fail-fast: false
      matrix:
        include:
          # SPM Build Matrix
          - runs-on: macos-14
            xcode: "/Applications/Xcode_15.0.app"

          - runs-on: macos-14
            xcode: "/Applications/Xcode_15.1.app"

          - runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"

          - runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"

          # macOS Build Matrix
          - type: macos
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.0.app"

          - type: macos
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.1.app"

          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"

          - type: macos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
                      
          # iOS Build Matrix
          - type: ios
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.0.app"
            deviceName: "iPhone 15"
            osVersion: "17.0"
            download-platform: true

          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "iPhone 16 Pro"
            osVersion: "18.4"
            download-platform: true
  
          - type: ios
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "iPhone 17 Pro"
            osVersion: "26.0"
            download-platform: true
  
          # watchOS Build Matrix
          - type: watchos
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.0.app"
            deviceName: "Apple Watch Series 9 (45mm)"
            osVersion: "10.0"
            download-platform: true

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Watch Ultra 2 (49mm)"
            osVersion: "11.4"
            download-platform: true

          - type: watchos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple Watch Ultra 3 (49mm)"
            osVersion: "26.0"
            download-platform: true

          # tvOS Build Matrix
          - type: tvos
            runs-on: macos-14
            xcode: "/Applications/Xcode_15.0.app"
            deviceName: "Apple TV"
            osVersion: "17.0"
            download-platform: true

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple TV"
            osVersion: "18.4"
            download-platform: true

          - type: tvos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple TV"
            osVersion: "26.0"
            download-platform: true

          # visionOS Build Matrix
          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_16.4.app"
            deviceName: "Apple Vision Pro"
            osVersion: "2.4"
            download-platform: true
              
          - type: visionos
            runs-on: macos-15
            xcode: "/Applications/Xcode_26.0.app"
            deviceName: "Apple Vision Pro"
            osVersion: "26.0"
            download-platform: true
  
    steps:
      - uses: actions/checkout@v4

      - name: Build and Test
        uses: brightdigit/swift-build@v1.3.4
        with:
          scheme: ${{ env.PACKAGE_NAME }}
          type: ${{ matrix.type }}
          xcode: ${{ matrix.xcode }}
          deviceName: ${{ matrix.deviceName }}
          osVersion: ${{ matrix.osVersion }}
          download-platform: ${{ matrix.download-platform }}
          
      # Common Coverage Steps
      - name: Process Coverage
        uses: sersoft-gmbh/swift-coverage-action@v4
  
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.type && format('{0}{1}', matrix.type, matrix.osVersion) || 'spm' }}

  lint:
    name: Linting
    if: "!contains(github.event.head_commit.message, 'ci skip')"  
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-macos, build-windows]
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin
    steps:
      - uses: actions/checkout@v4    
      - name: Cache mint
        id: cache-mint
        uses: actions/cache@v4  
        env:
          cache-name: cache
        with:
          path: |
            .mint
            Mint         
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-  
      - name: Install mint
        if: steps.cache-mint.outputs.cache-hit == ''
        run: |
          git clone https://github.com/yonaskolb/Mint.git
          cd Mint
          swift run mint install yonaskolb/mint
      - name: Lint
        run: ./Scripts/lint.sh